import '../styles/globals.css'
import Head from 'next/head'
import Nav from '../components/Nav';
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.tailgrids.com/tailgrids-fallback.css" />
      </Head>
      <div>
        <Nav />
        <Component {...pageProps} />
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            &copy; Asep Budiyana Muharam
          </a>
        </footer>
      </div>
    </>
  );
}

export default MyApp
